### PR TITLE
add initial draft of the logo assets

### PR DESCRIPTION
**Pull request by AidanGlickman**
added vector and raster versions of the logo for later use

### CODE REVIEW

**Comment by richyliu** [comment]
Should we standardize the background (color)?

**Review by reteps — APPROVED** [review]

**Comment by InnovativeInventor** [comment]
We should not rename files `Artboard 1` (e.g. `assets/logo/150w/Artboard 1ico.png`). Otherwise, it looks good to me.

**Review by richyliu — APPROVED** [review]
Should we standardize the background color?

**Review by InnovativeInventor — CHANGES_REQUESTED** [review]
Seems good -- logo looks clean and has university colors. You should consider implementing the suggestions I made, though.

**Review by InnovativeInventor — APPROVED** [review]

**Pull request merged**
